baseurl = "https://me.htr.app"
languageCode = "en-us"
title = "Classic"
theme = "hugo-classic"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Personal Website of Nianmin Guo"
    footer = "[hugo theme Github](https://github.com/goodroot/hugo-classic)"
    custom_css = ["css/theme-override.css"]
